#!/bin/bash

rm -rf hardwario-macos-installer/macOS-x64/application/code-portable-data/user-data/CachedExtensionVSIXs/

codesign --force --verify --timestamp --verbose --sign C32QFQ68V9 --options runtime hardwario-macos-installer/macOS-x64/application/code-portable-data/extensions/marus25.cortex-debug-*/binary_modules/electron-*/node_modules/lzma-native/prebuilds/darwin-arm64/electron.napi.node
codesign --force --verify --timestamp --verbose --sign C32QFQ68V9 --options runtime hardwario-macos-installer/macOS-x64/application/code-portable-data/extensions/ms-vscode.cpptools-*/debugAdapters/lldb/bin/lldb-mi
codesign --force --verify --timestamp --verbose --sign C32QFQ68V9 --options runtime hardwario-macos-installer/macOS-x64/application/code-portable-data/extensions/marus25.cortex-debug-*/binary_modules/electron-*/node_modules/lzma-native/prebuilds/darwin-x64/electron.napi.node
codesign --force --verify --timestamp --verbose --sign C32QFQ68V9 --options runtime hardwario-macos-installer/macOS-x64/application/code-portable-data/extensions/marus25.cortex-debug-*/binary_modules/electron-*/node_modules/@serialport/bindings-cpp/build/Release/obj.target/bindings/src/serialport_unix.o
codesign --force --verify --timestamp --verbose --entitlements ./entitlements.plist --sign C32QFQ68V9 --options runtime hardwario-macos-installer/macOS-x64/application/code-portable-data/extensions/ms-vscode.cpptools-*/bin/cpptools
codesign --force --verify --timestamp --verbose --sign C32QFQ68V9 --options runtime hardwario-macos-installer/macOS-x64/application/code-portable-data/extensions/marus25.cortex-debug-*/binary_modules/electron-*/node_modules/@serialport/bindings-cpp/build/Release/obj.target/bindings/src/darwin_list.o
codesign --force --verify --timestamp --verbose --sign C32QFQ68V9 --options runtime hardwario-macos-installer/macOS-x64/application/code-portable-data/extensions/marus25.cortex-debug-*/binary_modules/electron-*/node_modules/lzma-native/prebuilds/darwin-arm64/node.napi.node
codesign --force --verify --timestamp --verbose --sign C32QFQ68V9 --options runtime hardwario-macos-installer/macOS-x64/application/code-portable-data/extensions/marus25.cortex-debug-*/binary_modules/electron-*/node_modules/@serialport/bindings-cpp/build/Release/bindings.node
codesign --force --verify --timestamp --verbose --sign C32QFQ68V9 --options runtime hardwario-macos-installer/macOS-x64/application/code-portable-data/extensions/marus25.cortex-debug-*/binary_modules/electron-*/node_modules/@serialport/bindings-cpp/bin/darwin-x64-103/bindings-cpp.node
codesign --force --verify --timestamp --verbose --entitlements ./entitlements.plist --sign C32QFQ68V9 --options runtime hardwario-macos-installer/macOS-x64/application/code-portable-data/tower/toolchain/ninja/ninja
codesign --force --verify --timestamp --verbose --sign C32QFQ68V9 --options runtime hardwario-macos-installer/macOS-x64/application/code-portable-data/extensions/ms-vscode.cpptools-*/debugAdapters/lldb/bin/lldb-argdumper
codesign --force --verify --timestamp --verbose --sign C32QFQ68V9 --options runtime hardwario-macos-installer/macOS-x64/application/code-portable-data/extensions/hardwario.hardwario-tower-*/node_modules/@serialport/bindings-cpp/prebuilds/darwin-x64+arm64/node.napi.node
codesign --force --verify --timestamp --verbose --sign C32QFQ68V9 --options runtime hardwario-macos-installer/macOS-x64/application/code-portable-data/extensions/ms-vscode.cpptools-*/debugAdapters/lldb/bin/lldb-launcher
codesign --force --verify --timestamp --verbose --sign C32QFQ68V9 --options runtime hardwario-macos-installer/macOS-x64/application/code-portable-data/extensions/marus25.cortex-debug-*/binary_modules/electron-*/node_modules/@serialport/bindings-cpp/build/Release/obj.target/bindings/src/serialport.o
codesign --force --verify --timestamp --verbose --sign C32QFQ68V9 --options runtime hardwario-macos-installer/macOS-x64/application/code-portable-data/extensions/ms-vscode.cpptools-*/debugAdapters/lldb/bin/debugserver
codesign --force --verify --timestamp --verbose --sign C32QFQ68V9 --options runtime hardwario-macos-installer/macOS-x64/application/code-portable-data/extensions/marus25.cortex-debug-*/binary_modules/electron-*/node_modules/@serialport/bindings-cpp/build/Release/obj.target/bindings/src/poller.o
codesign --force --verify --timestamp --verbose --entitlements ./entitlements.plist --sign C32QFQ68V9 --options runtime hardwario-macos-installer/macOS-x64/application/code-portable-data/extensions/ms-vscode.cpptools-*/bin/cpptools-srv
codesign --force --verify --timestamp --verbose --sign C32QFQ68V9 --options runtime hardwario-macos-installer/macOS-x64/application/code-portable-data/extensions/marus25.cortex-debug-*/binary_modules/electron-*/node_modules/lzma-native/prebuilds/darwin-x64/node.napi.node
codesign --force --verify --timestamp --verbose --sign C32QFQ68V9 --options runtime hardwario-macos-installer/macOS-x64/application/code-portable-data/extensions/ms-vscode.cpptools-*/debugAdapters/lldb/lib/liblldb.*.dylib
codesign --force --verify --timestamp --verbose --sign C32QFQ68V9 --options runtime hardwario-macos-installer/macOS-x64/application/code-portable-data/extensions/marus25.cortex-debug-*/binary_modules/electron-*/node_modules/@serialport/bindings-cpp/prebuilds/darwin-x64+arm64/node.napi.node
codesign --force --verify --timestamp --verbose --sign C32QFQ68V9 --options runtime hardwario-macos-installer/macOS-x64/application/code-portable-data/extensions/hardwario.hardwario-tower-*/node_modules/@serialport/bindings-cpp/prebuilds/darwin-x64+arm64/node.napi.node
